"""initial

Revision ID: 7a9f56ee0cfb
Revises: 
Create Date: 2022-06-13 18:08:35.812794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9f56ee0cfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_changed', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depot_manifest',
    sa.Column('depot', sa.Integer(), nullable=False),
    sa.Column('manifest', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('depot', 'manifest')
    )
    op.create_table('build_depot',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('depot_manifest_depot', sa.Integer(), nullable=False),
    sa.Column('depot_manifest_manifest', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['build.id'], ),
    sa.ForeignKeyConstraint(['depot_manifest_depot', 'depot_manifest_manifest'], ['depot_manifest.depot', 'depot_manifest.manifest'], ),
    sa.PrimaryKeyConstraint('build_id', 'depot_manifest_depot', 'depot_manifest_manifest')
    )
    op.create_table('change_list_branch',
    sa.Column('change_list_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=True),
    sa.Column('time_updated', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['build.id'], ),
    sa.ForeignKeyConstraint(['change_list_id'], ['change_list.id'], ),
    sa.PrimaryKeyConstraint('change_list_id', 'name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_list_branch')
    op.drop_table('build_depot')
    op.drop_table('depot_manifest')
    op.drop_table('change_list')
    op.drop_table('build')
    # ### end Alembic commands ###
